export const discoverObj={
    id:'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Best In The World',
    headline: 'Current And Future Stars!',
    description: 'The best of the best! Find the best players of this year and the rising stars in the footballing world!',
    buttonLabel: 'Let\'s Go!',
    imgStart: true,
    img: require('../images/football.svg').default,
    alt: 'bdor',
    dark: false,
    primary: false,
    darkText: true,
    path: '/discover'
}
export const discoverObj1={
    id:'discover',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Young Talents',
    headline: 'Prospects',
    description: 'The best youngsters of the footballing world!',
    buttonLabel: 'Know More!',
    imgStart: false,
    img: require('../images/prospects3.png'),
    alt: 'hp',
    dark: true,
    primary: true,
    darkText: false,
    path: '/prospects'
}
export const discoverObj2={
    id:'discover2',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Best In The World',
    headline: 'Ballon D\'or Rankings',
    description: 'The best players of the year 2021',
    buttonLabel: 'Know More!',
    imgStart: true,
    img: require('../images/bdor.svg').default,
    alt: 'bdor',
    dark: false,
    primary: false,
    darkText: true,
    path: '/bdor'
}
export const aboutObj={
    id:'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Behind The Scenes',
    headline: 'About Us',
    description: 'A brief description of who\'s behind this awesome website. Not to brag but this is an awesome website, isn\'t it?',
    buttonLabel: 'Find Out!',
    imgStart: true,
    img: require('../images/pic2.svg').default,
    alt: 'ss',
    dark: false,
    primary: false,
    darkText: true, 
    path: '/aboutus'
}
export const aboutObj1={
    id:'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Front-End/Back-End',
    headline: 'Yashas N',
    description: 'Something about me.',
    buttonLabel: 'Me',
    imgStart: false,
    img: require('../images/pic2.svg').default,
    alt: 'yn',
    dark: true,
    primary: true,
    darkText: false
}
export const aboutObj2={
    id:'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Queries',
    headline: 'Syed',
    description: 'Something about him.',
    buttonLabel: 'Him',
    imgStart: true,
    img: require('../images/pic2.svg').default,
    alt: 'ss',
    dark: false,
    primary: false,
    darkText: true
}
export const signUpObj={
    id:'signup',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Join Us',
    headline: 'Become A Member!',
    description: 'Keep track of your favourite player and your favourite team by creating an account!',
    buttonLabel: 'Sign Up!',
    imgStart: false,
    img: require('../images/signup.svg').default,
    alt: 'yn',
    dark: true,
    primary: true,
    darkText: false,
    path: '/signup'
}